// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "src/verifier.sol"; // Import the verifier generated by snarkjs

contract NameVerifier {
    Groth16Verifier public verifierContract; // Instance of the generated Verifier contract

    constructor(address _verifierAddress) {
        verifierContract = Groth16Verifier(_verifierAddress); // Initialize the verifier contract
    }

    // A function to verify the proof with public inputs
    function verifyName(uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[1] memory input)
        public
        view
        returns (bool)
    {
        return verifierContract.verifyProof(a, b, c, input); // Calls the verifyProof function from the Verifier
    }
}
